security:
    encoders:
        App\Entity\Admin: plaintext
    providers:
        admin:
            entity:
                class: App\Entity\Admin
                property: name
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            form_login:
                login_path: login
                check_path: login
            logout:
                path: logout

    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
